version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:615496323698:task-definition/practice04:2"
        LoadBalancerInfo:
          ContainerName: "practice04-proxy"
          ContainerPort: 80