version: '3'

services:
  mongo_db:
    container_name: db_container
    image: 615496323698.dkr.ecr.ap-northeast-1.amazonaws.com/practice04-db:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    networks:
      - jh-network

  web-backend:
#    build: .
    image: 615496323698.dkr.ecr.ap-northeast-1.amazonaws.com/practice04-app:latest
#    ports:
#      - "3000:3000"
##    volumes:
##      - .:/usr/src/app
#    volumes:
#      - ./source:/source
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: web
    networks:
      - jh-network


  proxy:
    image: 615496323698.dkr.ecr.ap-northeast-1.amazonaws.com/practice04-proxy:latest
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
      - mongo_db
    networks:
      - jh-network


volumes:
  mongo_db: {}

networks:
  jh-network:
    external: true